# Specify the correct build directory - adjust if yours is different
[build]
  publish = "dist" # Change to "build" if you're using Create React App

# Proper MIME types for JavaScript files - more specific matchers
[[headers]]
  for = "/main.js"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/main.jsx"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/assets/*.mjs"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript"

# Ensure module scripts are properly handled
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript"
    Accept-Ranges = "bytes"

# Static asset handling
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Specific redirects for assets first
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
  force = true

# Handle SPA routing for React Router (this should be the LAST redirect)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200